---

- name: Zabbix Server
  hosts: zabbix_server
  become: yes
  vars_files: /etc/ansible/vars.yml
  tasks:

  - name: Stop Zabbix Agent
    systemd:
        name: "zabbix-server" 
        state: stopped

- name: Banco de dados
  hosts: db
  become: yes
  vars_files: /etc/ansible/vars.yml
  tasks:
    
    - name: Add PostgreSQL repository 1
      shell: |
        echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/timescaledb.list

    - name: Add PostgreSQL repository 2
      shell: |
        wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/timescaledb.gpg

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install timescaldb
      apt:
        name:  
          - timescaledb-2-postgresql-16=2.13.1~debian12 
          - timescaledb-2-loader-postgresql-16=2.13.1~debian12
        state: present
        update_cache: yes
    
    - name: Restart PostgreSQL service
      service:
        name: postgresql
        state: restarted

    - name: Set listen_addresses
      ansible.builtin.replace:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
          - { regexp: "^#shared_preload_libraries =.*", replace: "shared_preload_libraries = 'timescaledb'" } 

    - name: Restart PostgreSQL service
      service:
        name: postgresql
        state: restarted

    - name: Add PostgreSQL repository 1
      shell: |
        echo "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;" | sudo -u postgres psql zabbix

- name: Zabbix Server
  hosts: zabbix_server
  become: yes
  vars_files: /etc/ansible/vars.yml
  tasks:

    - name: Import Zabbix database schema
      shell: |
        cat /usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql | psql -h 192.168.15.10 -U zabbix -d zabbix
      environment:
        PGPASSWORD: "password"
      args:
        executable: /bin/bash

    - name: Enable/Start Zabbix Agent
      systemd:
        name: "zabbix-server" 
        state: started


...